name: Build and Push Docker Image to GitHub Container Registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Log in to GitHub Container Registry using the GitHub token
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Cache Docker layers to improve build speed
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Step 5: Build and push the Docker image to GitHub Container Registry
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.actor }}/global-md:latest  # Convert repo name to lowercase

      # Step 6 (optional): Test the Docker container by running it locally
      - name: Run the container (optional)
        run: docker run -d -p 3000:3000 ghcr.io/${{ github.actor }}/global-md:latest
